config/routes.rb
Rails.application.routes.draw do
	
	root 'users#index'
	devise_for :users
	resources :users, only: [:show, :index,]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_save { self.name.capitalize! }
  before_save { self.email.downcase! }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	
	validates :name, presence:true, length: { maximum: 50 }
	validates :description, presence:true, length: { maximum: 150 }

	has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	private

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :description, :avatar])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :description, :avatar])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'layouts/application/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
  <div class="container">
      <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        &#x2630;
      </button>

    <%= link_to 'User', root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="nav-item"><a href="#" class="nav-link">About</a>
          </li>
          <li class="nav-item"><a href="#" class="nav-link">Contacts</a>
          </li>
        </ul>
    <div class="navbar-nav ml-auto">
      <div class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <div class="nav-item">
              <span class="navbar-text">
                Hello, &nbsp;
              <span>
            </div>                  
              <div class="dropdown show">
                  <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                  </div>
                  
                <% else %>
                  <div class="nav-item">
                    <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                  </div>
            <div>
            <% end %>
            </div>
      </div>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Avanar</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.avatar, size: 100 if user.avatar.attached? %></td>
        <td><%= link_to user.name, user %></td>
        <td><%= user.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_registration_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<%= image_tag @user.avatar if @user.avatar.attached? %>
</p>

<p>
	<strong>Name:</strong>
	<%= @user.name %>
</p>

<p>
	<strong>Description:</strong>
	<%= @user.description %>
</p>
<% if user_signed_in? %>
	<% if current_user.id == @user.id %>
		<%= link_to 'Edit', edit_user_registration_path(@user) %> |
	<% end %>
<% end %>

<%= link_to 'Back', users_path %>